<a href="https://colab.research.google.com/github/zahid-bracu/buet-business-analytics/blob/main/Lecture_4_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Docs Index : https://docs.google.com/document/d/1Md0-O4CKjvpYbzzFP7dyooB0eJP2G5tAj4YUnQ2QWdo/edit?usp=sharing

####Import numpy and version check

In [1]:
import numpy as np
print(np.__version__)

1.25.2


####Creating Numpy Array From List

In [5]:
my_list=[1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9]
my_list=[[1.1,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]]
my_array=np.array(my_list,dtype=float)
print(my_array)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]


####Creating Numpy Array From Tuple

In [7]:
my_tuple=((11,22,33),(44,55,66),(77,88,99))
my_np_array=np.array(my_tuple)
print(my_np_array)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


####Generating arrays with specific values : Zeros
* 3 : Rows
* 4 : Columns

In [10]:
zeros_array_int=np.zeros((3,4),dtype=float)
zeros_array_int

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

####Generating arrays with specific values : Ones

In [11]:
ones_array_int=np.ones((3,4),dtype=float)
ones_array_int

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

####Generating arrays with Random Numbers

In [14]:
random_array_int=np.random.randint(10,21,size=(3,4))
random_array_int

array([[10, 16, 12, 11],
       [11, 16, 19, 16],
       [10, 15, 12, 13]])

####Generating arrays with Specific Number

In [15]:
custom_array=np.full((3,4),7)
custom_array

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])