<a href="https://colab.research.google.com/github/zahid-bracu/buet-business-analytics/blob/main/Lecture_4_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Docs Index : https://docs.google.com/document/d/1Md0-O4CKjvpYbzzFP7dyooB0eJP2G5tAj4YUnQ2QWdo/edit?usp=sharing

####Import numpy and version check

In [22]:
import numpy as np
print(np.__version__)

1.25.2


####Creating Numpy Array From List

In [23]:
my_list=[1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9]
my_list=[[1.1,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]]
my_array=np.array(my_list,dtype=float)
print(my_array)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]


####Creating Numpy Array From Tuple

In [24]:
my_tuple=((11,22,33),(44,55,66),(77,88,99))
my_np_array=np.array(my_tuple)
print(my_np_array)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


####Generating arrays with specific values : Zeros
* 3 : Rows
* 4 : Columns

In [25]:
zeros_array_int=np.zeros((3,4),dtype=float)
zeros_array_int

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

####Generating arrays with specific values : Ones

In [26]:
ones_array_int=np.ones((3,4),dtype=float)
ones_array_int

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

####Generating arrays with Random Numbers

In [27]:
random_array_int=np.random.randint(10,21,size=(3,4))
random_array_int

array([[11, 10, 15, 17],
       [14, 10, 20, 16],
       [17, 19, 10, 15]])

####Generating arrays with Specific Number

In [28]:
custom_array=np.full((3,4),7)
custom_array

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

####Array Indexing

In [29]:
index_array=np.array([0,1,2,3,4,5,6,7,8,9])
print(index_array[0])
print(index_array[-4])

index_array_2d=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(index_array_2d[1,2])
print(index_array_2d[-3,-3])

0
6
66
11


####Array Slicing

In [30]:
slice_array=[11,22,33,44,55,66,77,88,99]
print(slice_array[:5]) #1st to index 4
print(slice_array[3:]) #index 3 to last
print(slice_array[2:6]) #index 2 to index 5
print(slice_array[:-3]) #1st to 4th last
print(slice_array[-4:]) #4th last to last
print(slice_array[-6:-2]) #6th last to 3rd last
print(slice_array[2:-3]) #index 2 to 4th last
print(slice_array[-6:6]) #6th last to index 5

[11, 22, 33, 44, 55]
[44, 55, 66, 77, 88, 99]
[33, 44, 55, 66]
[11, 22, 33, 44, 55, 66]
[66, 77, 88, 99]
[44, 55, 66, 77]
[33, 44, 55, 66]
[44, 55, 66]


In [31]:
slice_array_2d=np.array([[11,22,33,111,222,333],[44,55,66,444,555,666],[77,88,99,777,888,999]])
print(slice_array_2d[1,1:4]) #index row 1 এর index 1 থেকে index 3

[ 55  66 444]


####Boolean Indexing

In [32]:
boolean_arr = np.array([11,22,33,3,55,4,77,1,2])
mask = boolean_arr > 5  # Create a mask based on a condition
result = boolean_arr[mask]  # Select elements greater than 5
print(result)

[11 22 33 55 77]


####Fancy Index

In [33]:
#1D Array
fancy_array=np.array([11,22,33,44,55,66,77,88,99])
indices=[0,2,4,6]
res=fancy_array[indices]
print(res)

#2D Array
fancy_array_2D=np.array([[11,22,33],[44,55,66],[77,88,99],[110,220,330]])
indices=[1,3]
res=fancy_array_2D[indices]
print(res)


#2D Array ****
fancy_array_2D=np.array([[11,22,33],[44,55,66],[77,88,99],[110,220,330]])
indices_row=[1,3]
indices_column=[1,1]
res=fancy_array_2D[indices_row,indices_column]
print(res)

[11 33 55 77]
[[ 44  55  66]
 [110 220 330]]
[ 55 220]


####Arithmetic Operations

In [34]:
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
res=arr1+arr2
print(res)

[5 7 9]


In [35]:
res_sub=arr1-arr2
print(res_sub)

[-3 -3 -3]


In [36]:
res_mult=arr1*arr2
print(res_mult)

[ 4 10 18]


In [37]:
res_div=arr1/arr2
print(res_div)

[0.25 0.4  0.5 ]


####Broadcasting

In [38]:
import numpy as np

# A 2x3 array
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# A 1x3 array
arr2 = np.array([10, 20, 30])

# Broadcasting arr2 to match the shape of arr1
result = arr1 * arr2

print(result)

[[ 10  40  90]
 [ 40 100 180]]


In [39]:
#Broadcasting
arr = np.array([1, 2, 3])
broadcasted_arr = np.broadcast_to(arr, (2, 3))
print(broadcasted_arr)
#This will create a 2x3 array where each row is a copy of the original array [1, 2, 3].

[[1 2 3]
 [1 2 3]]


####Array aggregation (sum, mean, max, min, etc.)


In [50]:
array_sum=np.array([[11,22,33],[44,55,66]])
sum=np.sum(array_sum)
print("Sum",sum)
mean=np.mean(array_sum)
print("Mean",mean)
min=np.min(array_sum)
print("Min",min)
max=np.max(array_sum)
print("Max",max)
std=np.std(array_sum)
print("Std",std)



Sum 231
Mean 38.5
Min 11
Max 66
Std 18.786076404259266


####Array concatenation and stacking

In [64]:
array_one=np.ones((2,3),int)
array_zeros=np.zeros((2,3))
array_block=np.block([array_one,array_zeros]) #horizontal concatenation
array_block

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [63]:
array_vstack=np.vstack([array_one,array_zeros]) #vertical concatenation
array_vstack

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])