<a href="https://colab.research.google.com/github/zahid-bracu/buet-iac-business-analytics/blob/main/Lecture_4_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Docs Index : https://docs.google.com/document/d/1Md0-O4CKjvpYbzzFP7dyooB0eJP2G5tAj4YUnQ2QWdo/edit?usp=sharing

####Import numpy and version check

In [ ]:
import numpy as np
print(np.__version__)

1.25.2


####Creating Simple Array

In [ ]:
a=[[11,22,33],[44,55,66],[77,88,99]]
b=[[111,222],[444,555],[777,888]]
print(a)
print(b)
print(a+b) #adding two simple array

[[11, 22, 33], [44, 55, 66], [77, 88, 99]]
[[111, 222], [444, 555], [777, 888]]
[[11, 22, 33], [44, 55, 66], [77, 88, 99], [111, 222], [444, 555], [777, 888]]


####Creating Numpy Array

In [ ]:
a=np.array([[11,22,33],[44,55,66]])
b=np.array([[111,222,999],[333,444,888]])
print(a)
print(b)


[[11 22 33]
 [44 55 66]]
[[111 222 999]
 [333 444 888]]


In [ ]:
c=a+b #adding two numpy array
print(c)

[[ 122  244 1032]
 [ 377  499  954]]


In [ ]:
d=c*10 #multiply with 10
print(d)

[[ 1220  2440 10320]
 [ 3770  4990  9540]]


####Idientity Matrix creation

In [ ]:
id=np.eye(2)
print(id)

[[1. 0.]
 [0. 1.]]


####Random Numpy Array Create

In [ ]:
a=np.random.randint(20,30,(2,3))
print(a)

[[20 24 28]
 [22 21 26]]


np.random.randint(10, 20, size=(2, 3)): This line generates a random integer array using NumPy's randint function. Here's what each argument does:
* 10: This is the lower bound (inclusive) of the random integers that can be generated.
* 20: This is the upper bound (exclusive) of the random integers that can be generated.
* size=(2, 3): This specifies the shape of the array to be generated. In this case, it creates a 2x3 array, meaning it has 2 rows and 3 columns.

####Random Numpy Array Create within range

In [30]:
y=[x for x in range(27)]
x=np.array([y])
print(x)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26]]


* y = [x for x in range(27)]: This line generates a list y containing numbers from 0 to 26 using list comprehension. The expression [x for x in range(27)] iterates over the numbers from 0 to 26 (inclusive) using range(27) and creates a list with those numbers.
* x = np.array([y]): Here, you're converting the list y into a NumPy array x. The expression np.array([y]) creates a NumPy array from the list y. The outer square brackets [] create a list with a single element, which is the list y, and then np.array() converts this list into a NumPy array.

####Array Shape Check

In [33]:
x.shape

(1, 27)

####Array Shape Reshaping

In [36]:
y = x.reshape((3, 9), order='F')
y

array([[ 0,  3,  6,  9, 12, 15, 18, 21, 24],
       [ 1,  4,  7, 10, 13, 16, 19, 22, 25],
       [ 2,  5,  8, 11, 14, 17, 20, 23, 26]])

* order='F': This parameter specifies the order in which elements are read from memory during reshaping. In this case, 'F' stands for Fortran order, which means the elements are read column by column.

In [37]:
z = x.reshape((3, 9), order='C')
z

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

* order='C': The order parameter specifies the order in which elements are read from memory during reshaping. In this case, 'C' stands for C-style order, which means the elements are read row by row.

####Changing data types

In [53]:
x=x.astype('int')
x.dtype

dtype('int64')

####Stack Building

In [60]:
a=[[11,22,33],[44,55,66],[77,88,99]]
b=[[111,222,333],[444,555,666],[777,888,999]]
c=[[110,220,330],[440,550,660],[770,880,990]]
d=np.hstack([a,b,c])
d

array([[ 11,  22,  33, 111, 222, 333, 110, 220, 330],
       [ 44,  55,  66, 444, 555, 666, 440, 550, 660],
       [ 77,  88,  99, 777, 888, 999, 770, 880, 990]])

* np.hstack: This function is a NumPy function used to horizontally stack arrays. It takes a sequence of arrays as input and stacks them horizontally (side by side) along the second axis.