<a href="https://colab.research.google.com/github/zahid-bracu/buet-iac-business-analytics/blob/main/Lecture_4_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Docs Index : https://docs.google.com/document/d/1Md0-O4CKjvpYbzzFP7dyooB0eJP2G5tAj4YUnQ2QWdo/edit?usp=sharing

####Import numpy and version check

In [16]:
import numpy as np
print(np.__version__)

1.25.2


####Creating Simple Array

In [17]:
a=[[11,22,33],[44,55,66],[77,88,99]]
b=[[111,222],[444,555],[777,888]]
print(a)
print(b)
print(a+b) #adding two simple array

[[11, 22, 33], [44, 55, 66], [77, 88, 99]]
[[111, 222], [444, 555], [777, 888]]
[[11, 22, 33], [44, 55, 66], [77, 88, 99], [111, 222], [444, 555], [777, 888]]


####Creating Numpy Array

In [18]:
a=np.array([[11,22,33],[44,55,66]])
b=np.array([[111,222,999],[333,444,888]])
print(a)
print(b)


[[11 22 33]
 [44 55 66]]
[[111 222 999]
 [333 444 888]]


In [19]:
c=a+b #adding two numpy array
print(c)

[[ 122  244 1032]
 [ 377  499  954]]


In [20]:
d=c*10 #multiply with 10
print(d)

[[ 1220  2440 10320]
 [ 3770  4990  9540]]


####Idientity Matrix creation

In [21]:
id=np.eye(2)
print(id)

[[1. 0.]
 [0. 1.]]
